name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build system and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatchling
          pip install -e .  # installs your package and dependencies

      - name: Run placeholder test step
        run: echo "No tests yet, but the environment is set up!"

